name = "trenches"
main = "worker/index.js"
compatibility_date = "2026-07-01"
workers_dev = true

[assets]
directory = "./"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "TrenchesLobby"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TrenchesLobby"]
